### ISSUE TITLE
hi, could you share the whole android demo for me ?

### ISSUE THREAD

**Issue by chenweiqian** [Nilhcem/tensorflow-classifier-android#1]
hello, i have tried several days to build the demo. but i failed. 
when i use bazel, it succeed. However, it' failed with android studio. I don't know why.
And i try your project, it can run successfully. So i want you can share the whole android demo for me.
Thanks !!  I wish you a happy!

**Comment by Nilhcem** [comment]
I've updated the sample project to be compatible with TensorFlow 1.2. This is a working demo.  
I've also updated the article: http://nilhcem.com/android/custom-tensorflow-classifier
Hope that it's more clear now

**Comment by chenweiqian** [comment]
Thank you!
