### ISSUE TITLE
Could it only change the .pb and .txt ?

### ISSUE THREAD

**Issue by LtveG** [Nilhcem/tensorflow-classifier-android#2]
HI, I train my own .pb and .txt files, and replace its origin pb and txt . BUT when  i run it on Android ,the android studio give a error : 

E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate()

Whether it has to build the .so and .jar by myself ?

Thank you very much

**Comment by Nilhcem** [comment]
I've updated the project to use TensorFlow 1.2 which does not need .so and .jar anymore inside the project (but via a gradle dependency).

The article was also modified to make things more clear with TensorFlow 1.2.
http://nilhcem.com/android/custom-tensorflow-classifier

If you run the new sample, you may still find this "E/art RunStat" error on the logs but it won't have an impact on the app (this should work)
